import "./globals.css";
import LayoutClient from "./layout-client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased font-sans`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
